### ISSUE TITLE
Feature request: slugify

### ISSUE THREAD

**Issue by Ginden** [qarmin/szyszka#42]
Three problems: 

* certain programs break when confronted with file names containing non-ASCII (this is especially visible for Windows - eg. username `Michał` will lead you in trouble, because some files will end in `C:\Users\Micha\` and others will end in `C:\Users\Michał\`)

* certain programs break when confronted with file names containing colons (it breaks Windows on OS level and causes trouble for `rsync`) or spaces (these are just poorly written).

My suggestion is to provide way to normalize file names - using algorithm similar to eg. [slug](https://www.npmjs.com/package/slug).

**Comment by qarmin** [comment]
Normalizing names I implemented in https://github.com/qarmin/szyszka/pull/47

This is only an option and users may do whatever they want with files(if they want to have colons or spaces in names I won't stop them since this is not my data).

I'm using [slugmin](https://github.com/qarmin/slugmin) my fork of [slug-rs](https://github.com/Stebalien/slug-rs) library which allows to use `_`, ` `(space ) and `.`, since I think this characters are useful(anyone can use replace rule to remove them).
