### ISSUE TITLE
Unable to get creation date from file

### ISSUE THREAD

**Issue by ryansalerno** [qarmin/szyszka#59]
On an XFS and NFS-mounted-XFS partition, I'm unable to add any files and the only output when run in the terminal is `Unable to get creation date from file`

Adding files from an ext4 partition works fine.

In the absence of tracking down and fixing the specific problem, I'd love to be able to use the program without the creation date magic replacement variable (or have it just fill zeroes instead of rejecting the file completely).

**Comment by qarmin** [comment]
To read file metadata I use functions from standard rust library, so it is quite unlikely that this functions are bugged(but not impossible) so probably error with permissions happens or something similar.

Since https://github.com/qarmin/szyszka/commit/f387a69b8756384670e4d91ebedd03971fa4a876 files with such error aren't ignored anymore
