### ISSUE TITLE
No dark theme for 3.0.0?

### ISSUE THREAD

**Issue by AlphaHasher** [qarmin/szyszka#73]

**Comment by qarmin** [comment]
App uses system theme(maybe except snap/flatpak and alternative appimage build)

![Screenshot from 2023-05-24 20-27-59](https://github.com/qarmin/szyszka/assets/41945903/e3be0564-614e-4eec-8951-61142b0c43ba)
![Screenshot from 2023-05-24 20-28-03](https://github.com/qarmin/szyszka/assets/41945903/3a6f8dc9-15b5-47fc-b7da-95e1a1c7a86c)

**Comment by qarmin** [comment]
Dark theme was enabled by default in windows build, but I disabled it, because it is broken(at least on Windows 10 VM).

This is instruction from CI how to manually enable dark mode
https://github.com/qarmin/szyszka/blob/b7c552c96cc8572981ae946aad87fae284832277/.github/workflows/windows.yml#L61-L66

Adding prebuild themes to be able to modify it from app is quite complicated task, so I don't plan to implement it in future(but maybe someone will be able to do this)

![Screenshot from 2023-05-24 21-01-42](https://github.com/qarmin/szyszka/assets/41945903/57d0fd36-f3a0-4959-9207-8922a5a18a5e)

after a while I see this 

![Screenshot from 2023-05-24 21-03-55](https://github.com/qarmin/szyszka/assets/41945903/fde58fbc-c46a-464f-adc5-290bea670135)

Probably other GTK 4 themes should work fine

**Comment by ajz3d** [comment]
On my end (Gnome 43) neither `szyszka_linux`, `szyszka.AppImage` nor the Flatpak version are detecting system's Light/Dark mode. They all default to light theme. What might be the culprit?

**Comment by DJCrashdummy** [comment]
my tests showed, that the AUR package on Arch - no matter if on a machine with KDE or Gnome - detects and uses the dark theme as expected, but the Flatpak doesn't. although other Flatpaks use perfectly fine the dark theme no matter if they use QT or GTK.

BTW @qarmin: it is exactly the same for Czkawka 9.0.0... but there seems to be an open issue https://github.com/qarmin/czkawka/issues/812 more or less about that.
also [a comment](https://github.com/qarmin/czkawka/issues/812#issuecomment-1641895989) indicates that the issue is that the Flatpaks don't have access to resp. get the (correct) environment variable.
